# Generated by Django 3.1.2 on 2020-11-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academictitle',
            options={'verbose_name_plural': 'academic titles'},
        ),
        migrations.AlterModelOptions(
            name='engagement',
            options={'verbose_name_plural': 'engagements'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name_plural': 'professors'},
        ),
        migrations.AlterModelOptions(
            name='professorinfo',
            options={'verbose_name': "professor's information"},
        ),
        migrations.AlterModelOptions(
            name='workstatus',
            options={'verbose_name_plural': 'work statuses'},
        ),
        migrations.AlterModelOptions(
            name='xprofessorsubject',
            options={'verbose_name': 'professor subject information'},
        ),
        migrations.AlterField(
            model_name='professorinfo',
            name='dissertation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='dissertation'),
        ),
    ]
