# Generated by Django 3.1.4 on 2021-02-05 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='academic_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='professors.academictitle', verbose_name='academic title'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='professors.engagement', verbose_name='engagement'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='work_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='professors.workstatus', verbose_name='work status'),
        ),
    ]
