# Generated by Django 3.1.4 on 2021-02-26 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0002_auto_20210205_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, unique=True, verbose_name='calling')),
            ],
            options={
                'verbose_name': 'calling',
                'verbose_name_plural': 'callings',
            },
        ),
        migrations.RemoveField(
            model_name='professor',
            name='calling',
        ),
        migrations.AddField(
            model_name='professor',
            name='calling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='professors.calling', verbose_name='calling'),
        ),
    ]
