# Generated by Django 3.1.4 on 2020-12-03 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20201203_1001'),
        ('professors', '0002_auto_20201104_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academictitle',
            options={'verbose_name': 'academic title', 'verbose_name_plural': 'academic titles'},
        ),
        migrations.AlterModelOptions(
            name='engagement',
            options={'verbose_name': 'engagement', 'verbose_name_plural': 'engagements'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'professor', 'verbose_name_plural': 'professors'},
        ),
        migrations.AlterModelOptions(
            name='professorinfo',
            options={'verbose_name': "professor's information", 'verbose_name_plural': 'professors information'},
        ),
        migrations.AlterModelOptions(
            name='workstatus',
            options={'verbose_name': 'work status', 'verbose_name_plural': 'work statuses'},
        ),
        migrations.AlterModelOptions(
            name='xprofessorsubject',
            options={'verbose_name': 'professor subject information', 'verbose_name_plural': 'professor subjects information'},
        ),
        migrations.AlterField(
            model_name='professorinfo',
            name='academic_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='professors.academictitle', verbose_name='academic title'),
        ),
        migrations.AlterField(
            model_name='professorinfo',
            name='engagement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='professors.engagement', verbose_name='engagement'),
        ),
        migrations.AlterField(
            model_name='professorinfo',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professors.professor', verbose_name='professor'),
        ),
        migrations.AlterField(
            model_name='professorinfo',
            name='work_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='professors.workstatus', verbose_name='work status'),
        ),
        migrations.AlterField(
            model_name='xprofessorsubject',
            name='practice',
            field=models.BooleanField(blank=True, default=False, verbose_name='practice'),
        ),
        migrations.AlterField(
            model_name='xprofessorsubject',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='professors.professor', verbose_name='professor'),
        ),
        migrations.AlterField(
            model_name='xprofessorsubject',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.subject', verbose_name='subject'),
        ),
    ]
