# Generated by Django 3.1.4 on 2021-03-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_auto_20210226_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, verbose_name='modification date'),
        ),
    ]
