# Generated by Django 3.1.4 on 2020-12-11 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0004_auto_20201203_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professorinfo',
            name='contract',
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
