# Generated by Django 3.1.4 on 2020-12-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0006_auto_20201222_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
    ]
