# Generated by Django 3.1.4 on 2020-12-22 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0007_professor_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='academic_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='professors.academictitle', verbose_name='academic title'),
        ),
        migrations.AddField(
            model_name='professor',
            name='dissertation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='dissertation'),
        ),
        migrations.AddField(
            model_name='professor',
            name='engagement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='professors.engagement', verbose_name='engagement'),
        ),
        migrations.AddField(
            model_name='professor',
            name='work_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='professors.workstatus', verbose_name='work status'),
        ),
        migrations.DeleteModel(
            name='ProfessorInfo',
        ),
    ]
