# Generated by Django 3.1.4 on 2020-12-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0008_auto_20201222_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='deleted',
        ),
        migrations.AddField(
            model_name='professor',
            name='inactive',
            field=models.BooleanField(default=False, verbose_name='neaktivan'),
        ),
    ]
