# Generated by Django 3.1.4 on 2020-12-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0011_auto_20201223_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
