# Generated by Django 3.1.4 on 2021-01-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0014_auto_20210112_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
