# Generated by Django 3.1.4 on 2021-01-18 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0015_professor_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='deactivation_date',
        ),
    ]
