# Generated by Django 3.1.4 on 2021-02-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0016_remove_professor_deactivation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='name',
            field=models.CharField(max_length=65, unique=True, verbose_name='engagement'),
        ),
        migrations.AlterField(
            model_name='workstatus',
            name='name',
            field=models.CharField(max_length=65, unique=True, verbose_name='work status'),
        ),
    ]
