# Generated by Django 3.1.4 on 2021-02-05 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='faculty')),
                ('short', models.CharField(max_length=10, unique=True, verbose_name='short')),
            ],
            options={
                'verbose_name': 'faculty',
                'verbose_name_plural': 'faculties',
                'ordering': ['short'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='semester')),
            ],
            options={
                'verbose_name': 'semester',
                'verbose_name_plural': 'semesters',
            },
        ),
        migrations.CreateModel(
            name='StudyCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='study cycle')),
            ],
            options={
                'verbose_name': 'study cycle',
                'verbose_name_plural': 'study cycles',
            },
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='study program')),
                ('short', models.CharField(max_length=10, unique=True, verbose_name='short')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.faculty', verbose_name='faculty')),
                ('study_cycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.studycycle', verbose_name='study cycle')),
            ],
            options={
                'verbose_name': 'study program',
                'verbose_name_plural': 'study programs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='subject type')),
            ],
            options={
                'verbose_name': 'subject type',
                'verbose_name_plural': 'subject types',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='datum kreiranja')),
                ('modification_date', models.DateTimeField(auto_now=True, verbose_name='datum izmjene')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='subject')),
                ('ects', models.IntegerField(verbose_name='ects')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('semester', models.ManyToManyField(to='subjects.Semester')),
                ('study_program', models.ManyToManyField(to='subjects.StudyProgram')),
                ('subject_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.subjecttype', verbose_name='subject type')),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
                'ordering': ['name'],
            },
        ),
    ]
