# Generated by Django 3.1.2 on 2020-11-02 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ects', models.IntegerField(default=5, unique=True, verbose_name='european credit transfer system')),
                ('name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='faculty')),
                ('short', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'ordering': ['short'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='semester')),
            ],
        ),
        migrations.CreateModel(
            name='StudyCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='study cycle')),
            ],
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='study program')),
                ('short', models.CharField(max_length=10, unique=True)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.faculty')),
                ('study_cycle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.studycycle')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='subject type')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='subject')),
                ('ects', models.ManyToManyField(to='subjects.Ects')),
                ('semester', models.ManyToManyField(to='subjects.Semester')),
                ('study_program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.studyprogram')),
                ('subject_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.subjecttype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
