# Generated by Django 3.1.4 on 2021-03-01 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.faculty', verbose_name='faculty'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.ManyToManyField(related_name='subjects', related_query_name='subject', to='subjects.Semester'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='study_program',
            field=models.ManyToManyField(related_name='subjects', related_query_name='subject', to='subjects.StudyProgram'),
        ),
    ]
