# Generated by Django 3.1.2 on 2020-11-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['short'], 'verbose_name_plural': 'faculties'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name_plural': 'semesters'},
        ),
        migrations.AlterModelOptions(
            name='studycycle',
            options={'verbose_name_plural': 'study cycles'},
        ),
        migrations.AlterModelOptions(
            name='studyprogram',
            options={'ordering': ['name'], 'verbose_name_plural': 'study programs'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name_plural': 'subjects'},
        ),
        migrations.AlterModelOptions(
            name='subjecttype',
            options={'verbose_name_plural': 'subject types'},
        ),
        migrations.AlterField(
            model_name='faculty',
            name='short',
            field=models.CharField(max_length=10, unique=True, verbose_name='short'),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='ects',
        ),
        migrations.AddField(
            model_name='subject',
            name='ects',
            field=models.IntegerField(default=5, verbose_name='ects'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ects',
        ),
    ]
