# Generated by Django 3.1.4 on 2021-03-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20210301_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studycycle',
            name='name',
        ),
        migrations.AddField(
            model_name='studycycle',
            name='number',
            field=models.IntegerField(default=1, unique=True, verbose_name='number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, verbose_name='modification date'),
        ),
    ]
