# Generated by Django 3.1.4 on 2020-12-03 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20201103_1459'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['short'], 'verbose_name': 'faculty', 'verbose_name_plural': 'faculties'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name': 'semester', 'verbose_name_plural': 'semesters'},
        ),
        migrations.AlterModelOptions(
            name='studycycle',
            options={'verbose_name': 'study cycle', 'verbose_name_plural': 'study cycles'},
        ),
        migrations.AlterModelOptions(
            name='studyprogram',
            options={'ordering': ['name'], 'verbose_name': 'study program', 'verbose_name_plural': 'study programs'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'subject', 'verbose_name_plural': 'subjects'},
        ),
        migrations.AlterModelOptions(
            name='subjecttype',
            options={'verbose_name': 'subject type', 'verbose_name_plural': 'subject types'},
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.faculty', verbose_name='faculty'),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='short',
            field=models.CharField(max_length=10, unique=True, verbose_name='short'),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='study_cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.studycycle', verbose_name='study cycle'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.subjecttype', verbose_name='subject type'),
        ),
    ]
