# Generated by Django 3.1.4 on 2020-12-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_auto_20201223_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='inactive',
        ),
        migrations.AddField(
            model_name='subject',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
