# Generated by Django 3.1.4 on 2021-01-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_auto_20201223_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='active',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='deletion_date',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='modification_date',
        ),
    ]
